language: cpp
compiler: gcc
language: cpp
sudo: required
dist: trusty
os: linux


before_install:
    - echo Install dependencies
    - sudo apt-get -qq update
    - sudo apt-get -q -y install libusb-1.0-0-dev libcfitsio3-dev libnova-dev
    - sudo apt-get -q -y install libgphoto2-dev libgps-dev libjpeg-dev cdbs
    - sudo apt-get -q -y install libopenal-dev libgsl0-dev libboost-dev
    - sudo apt-get -q -y install libboost-regex-dev libftdi-dev dcraw fakeroot wget

install:
    - ./travis-ci.sh 
    
script:
    - cd /home/travis/build/A-j-K/indi/build/libindi/test
    - ctest -V
    

